{% set name = "libxfoil" %}
{% set version = "1.0" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    url: https://github.com/montagdude/{{ name }}/archive/{{ version }}.tar.gz
    sha256: "1e251aac259bac84aa5be318ae62a496b705c625f0e54c44af230494904858ac"

build:
    number: 3
    skip: true  # [py<37]

outputs:

  - name: libxfoil
    script: build_lib.bat  # [win]
    script: build_lib.sh  # [not win]

    requirements:
        build:
            - {{ compiler("c") }}              # [unix]
            - {{ compiler("fortran") }}        # [unix]
            - {{ compiler("m2w64_c") }}        # [win]
            - {{ compiler('m2w64_fortran') }}  # [win]
            - cmake


  - name: pyxfoil
    script: build_py.bat  # [win]
    script: build_py.sh  # [not win]
    requirements:
        build:
            - {{ compiler("c") }}
            - swig
        host:
            - python
            - libxfoil
        run:
            - python

    test:
      imports:
        - xfoil_interface

about:
    home: https://github.com/montagdude/libxfoil
    license: GPL-2.0-only
    license_family: GPL
    license_file: LICENSE
    summary: libxfoil (xfoil + python bindings)
    description: libxfoil is a library to analyze the aerodynamics of 2-dimensional airfoi
                 sections programmatically using the Xfoil aerodynamics engine. 
    doc_url: https://github.com/montagdude/libxfoil
    dev_url: https://github.com/montagdude/libxfoil

extra:
  recipe-maintainers:
    - looooo
